version: 2

sources:
    - name: general
      database: "{{ env_var('SOURCE_DATABASE') }}"
      schema: RAW_MODEL_1
      description: Sources
      tables:
        - name: raw_model_1
        - name: raw_model_2