version: 2

sources:
    - name: general
      database: "{{ var('source_database') }}"
      schema: "{{ var('source_schema') }}"
      description: Sources
      tables:
        - name: source_data1